name: train-hyperparameter-tune-deploy-with-pytorch
dependencies:
- pip:
  - azureml-sdk
  - azureml-widgets
  - pillow==5.4.1
  - matplotlib
  - numpy==1.19.3
  - https://download.pytorch.org/whl/cpu/torch-1.6.0%2Bcpu-cp36-cp36m-win_amd64.whl
  - https://download.pytorch.org/whl/cpu/torchvision-0.7.0%2Bcpu-cp36-cp36m-win_amd64.whl
